### ISSUE TITLE
Enable Cloud Mode and Zookeper

### ISSUE THREAD

**Issue by nopenopenope** [docker-solr/docker-solr#180]
Is there any possibility to enable Cloud Mode with ZK in Docker?

**Comment by makuk66** [comment]
Sure, just pass the appropriate arguments just like you do in standard Solr. To just run in cloud mode, using the embedded zookeeper, you could do:

```
docker run -it -p 8983:8983 solr:7 -DzkRun
```
If you then go to to http://localhost:8983/ you can create a collection in the UI, and the click on the cloud graph.

**Comment by nopenopenope** [comment]
How would I do this in Docker-compose while using my custom config and embedded zookeeper? I use the following setup, however, ZK keeps telling me that it cannot connect to the host.
```

solr_1     | WARN  - 2018-07-04 08:13:07.404; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
solr_1     | java.net.ConnectException: Connection refused
solr_1     | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
solr_1     | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
solr_1     | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
solr_1     | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
solr_1     | WARN  - 2018-07-04 08:13:08.505; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
solr_1     | java.net.ConnectException: Connection refused
solr_1     | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
solr_1     | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
solr_1     | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
solr_1     | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)

```
This is my entrypoints configs:
```
./bin/solr start -cloud -p 8983 -s /opt/solr/server/solr/cloud/node1/solr -force -a "-Djute.maxbuffer=6291456"
./bin/solr zk upconfig -z 127.0.0.1:9983 -n default -d /opt/solr/server/solr/configsets/default
```

**Comment by makuk66** [comment]
If you are running those two commands in separate containers, which have separate network stacks, then that won't work; you'd have to point your upconfig container at the solr container or arrange to share network stacks. You also have a dependency issue, in that Solr's ZooKeeper needs to be running before you want to run your upconfig.

Here is an example that runs Solr, does an upconfig, then creates a collection:

```
version: '3'
services:
  mysolr:
    image: "solr:7"
    ports:
     - "8983:8983"
     - "9983:9983"
    command: solr -f -cloud
  upconfig:
    image: "solr:7"
    depends_on:
      - "mysolr"
    network_mode: "service:mysolr"
    command: bash -c "set -x; export; wait-for-solr.sh; solr zk upconfig -n myconf -d /opt/solr/server/solr/configsets/_default; bash -x bin/solr create_collection -p 8983 -c mycollection -n myconf"
```

Note the `network_mode`, which runs this container with the same network stack as Solr, so that when it connects to the default localhost for Solr and ZooKeeper everything just works.

**Comment by nopenopenope** [comment]
I'm very sorry but this does not seem to make any sense, or at least I guess I don't get it right. I'd be great if you could help me to sort this out.

From what I understand Zookeeper needs to be able to access either "localhost" (when using embedded ZK client) or the name of the service (which is available to other containers when using docker compose, i.e. "zookeeper").

I have this configuration right now in my `docker-compose.yml`:

```
solr:
    image: "solr:7.3"
    ports:
     - "8983:8983"
     - "9983:9983"
    command: solr -f -cloud -s /opt/solr/server/solr/cloud/node1/solr
    volumes:
      - ./docker/builds/solr/7.1/cloud/:/opt/solr/server/solr/cloud

  zookeeper:
    image: "solr:7.3"
    depends_on:
      - "solr"
    network_mode: "service:solr"
    command: bash -c "set -x; export; wait-for-solr.sh; solr zk upconfig -z localhost:9983 -n default -d /opt/solr/server/solr/configsets/_default;"
    volumes:
      - ./docker/builds/solr/7.1/configsets/default/:/opt/solr/server/solr/configsets/_default
      - ./docker/builds/solr/7.1/configsets/default/:/opt/solr/server/solr/configsets/default
```

Which leads to:

```
zookeeper_1   | WARN  - 2018-07-04 15:52:07.295; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:08.397; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:08.499; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:09.601; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:09.703; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:10.805; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:10.907; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:12.009; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:12.111; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:13.213; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:13.315; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:14.417; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:14.519; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:15.622; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:15.724; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:16.826; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:16.928; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:18.030; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:18.131; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:19.234; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | WARN  - 2018-07-04 15:52:19.335; org.apache.zookeeper.ClientCnxn$SendThread; Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
zookeeper_1   | java.net.ConnectException: Connection refused
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper_1   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
zookeeper_1   | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
zookeeper_1   | ERROR - 2018-07-04 15:52:20.550; org.apache.solr.util.SolrCLI$ConfigSetUploadTool; Could not complete upconfig operation for reason: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper localhost:9983 within 30000 ms
zookeeper_1   | 
zookeeper_1   | ERROR: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper localhost:9983 within 30000 ms
zookeeper_1   | 
projectnamespace_zookeeper_1 exited with code 1
```
So this does not work. See the docker-compose content, I've just made slightly changes and added my nodes to the container, as solr is unable to create them himself. (SOLR_HOME not found, when node dirs are not there). 



However, if I do it this way:

docker-compose.yml
```
  solr:
    build: ./docker/builds/solr
    ports:
     - "8983:8983"
     - "8984:8984"
    links:
      - "zookeeper"

  zookeeper:
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
```
./docker/builds/solr/Dockerfile
```
FROM solr:7.3

RUN rm -rf /opt/solr/server/solr/*

COPY ./etc/entrypoint.sh /opt/solr/entrypoint-solr.sh
COPY ./etc/core.properties /opt/solr/server/solr/
COPY ./7.1/cloud /opt/solr/server/solr/cloud/
COPY ./7.1/configsets/default /opt/solr/server/solr/configsets/default
COPY ./7.1/configsets/default /opt/solr/server/solr/configsets/_default

ENTRYPOINT /opt/solr/entrypoint-solr.sh
```

entrypoint.sh
```
#!/bin/sh

set -e

cd /opt/solr/
./bin/solr start -z zookeeper:2181 -p 8983 -s /opt/solr/server/solr/cloud/node1/solr -force -a "-Djute.maxbuffer=6291456"
./bin/solr zk upconfig -z zookeeper:2181 -n default -d ./server/solr/configsets/default -a "-Djute.maxbuffer=6291456"
./bin/solr start -z zookeeper:2181 -p 8984 -s /opt/solr/server/solr/cloud/node2/solr -force -a "-Djute.maxbuffer=6291456"

echo "Start Solr Logging"
tail -f -n 1 /opt/solr/server/logs/solr.log

exec docker-entrypoint.sh "$@"
```

it seems to run. However, from there on it cannot persist any data (I'll get a different error message when using it this way). 

I feel like the solution can't be too hard from here on, but somehow I don't see whats wrong. I'm sorry if this is extending the scope of Github way to much, but this topic really turns my head it. :(

**Comment by nopenopenope** [comment]
Additional:

if you copypaste the "upconfig"-node with any modifications, it says that it needs `-z`. 

If `-z` is provided it exits with code 0 after init, so this cannot be the solution either. :(
