### ISSUE TITLE
Docker-Solr in Azure - Underlying file changed by an external force at 1970-01-01T00:00:00Z

### ISSUE THREAD

**Issue by ijmac3** [docker-solr/docker-solr#250]
Hi, we are in the process of moving our application into Microsoft Azure but have been having an issue with solr.

We are running `docker-solr 8.2` and have found that, occasionally, attempting to add or remove an item from the index will cause solr to fall over and endlessly throw the exception below. 
It seems that some process is modifying the `write.lock` file in such a way that it believes it was modified at the epoch. (`Underlying file changed by an external force at 1970-01-01T00:00:00Z`)
Restarting solr fixes the issue for a while though it will eventually happen again.

Stack trace is as follows:
```
2019-10-02 12:21:56.798 ERROR (qtp2082351661-25) [   x:global] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Server error writing document id 2133 to the index
 	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:241)
 	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:76)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:257)
 	at org.apache.solr.update.processor.DistributedUpdateProcessor.doVersionAdd(DistributedUpdateProcessor.java:487)
 	at org.apache.solr.update.processor.DistributedUpdateProcessor.lambda$versionAdd$0(DistributedUpdateProcessor.java:337)
 	at org.apache.solr.update.VersionBucket.runWithLock(VersionBucket.java:50)
 	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:337)
 	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:223)
 	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:103)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.AddSchemaFieldsUpdateProcessorFactory$AddSchemaFieldsUpdateProcessor.processAdd(AddSchemaFieldsUpdateProcessorFactory.java:475)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.FieldMutatingUpdateProcessor.processAdd(FieldMutatingUpdateProcessor.java:118)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.FieldMutatingUpdateProcessor.processAdd(FieldMutatingUpdateProcessor.java:118)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.FieldMutatingUpdateProcessor.processAdd(FieldMutatingUpdateProcessor.java:118)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.FieldMutatingUpdateProcessor.processAdd(FieldMutatingUpdateProcessor.java:118)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.FieldNameMutatingUpdateProcessorFactory$1.processAdd(FieldNameMutatingUpdateProcessorFactory.java:75)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.FieldMutatingUpdateProcessor.processAdd(FieldMutatingUpdateProcessor.java:118)
 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
 	at org.apache.solr.update.processor.AbstractDefaultValueUpdateProcessorFactory$DefaultValueUpdateProcessor.processAdd(AbstractDefaultValueUpdateProcessorFactory.java:92)
 	at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:110)
 	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:327)
 	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readIterator(JavaBinUpdateRequestCodec.java:280)
 	at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:336)
 	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:281)
 	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readNamedList(JavaBinUpdateRequestCodec.java:235)
 	at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:301)
 	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:281)
 	at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:194)
 	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:126)
 	at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:123)
 	at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:70)
 	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
 	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
 	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
 	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2578)
 	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:780)
 	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:566)
 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:423)
 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:350)
 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 	at org.eclipse.jetty.server.Server.handle(Server.java:505)
 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
 	at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
 	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:681)
 	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:695)
 	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1591)
 	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1586)
 	at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:964)
 	at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:342)
 	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:289)
 	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:236)
 	... 79 more
 Caused by: org.apache.lucene.store.AlreadyClosedException: Underlying file changed by an external force at 1970-01-01T00:00:00Z, (lock=NativeFSLock(path=/solr_config/data/global/data/index/write.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2019-10-02T11:52:59Z))
 	at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:191)
 	at org.apache.lucene.store.LockValidatingDirectoryWrapper.createOutput(LockValidatingDirectoryWrapper.java:43)
 	at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:43)
 	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.<init>(CompressingStoredFieldsWriter.java:112)
 	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsWriter(CompressingStoredFieldsFormat.java:128)
 	at org.apache.lucene.codecs.lucene50.Lucene50StoredFieldsFormat.fieldsWriter(Lucene50StoredFieldsFormat.java:183)
 	at org.apache.lucene.index.StoredFieldsConsumer.initStoredFieldsWriter(StoredFieldsConsumer.java:39)
 	at org.apache.lucene.index.StoredFieldsConsumer.startDocument(StoredFieldsConsumer.java:46)
 	at org.apache.lucene.index.DefaultIndexingChain.startStoredFields(DefaultIndexingChain.java:367)
 	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:403)
 	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:250)
 	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:495)
 	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1594)
 	... 84 more
```

We only have one solr instance and our write.lock and all other config/data files are in blob storage on azure that should only accessible by this instance. 

Any advice or suggestions would be appreciated.
Thanks.

**Comment by makuk66** [comment]
I see this was also posted to https://stackoverflow.com/questions/58202028/docker-solr-container-on-azure-write-lock-file-is-being-changed-by-an-external

I found https://discuss.elastic.co/t/es-cluster-in-docker-containers-alreadyclosedexception-underlying-file-changed-by-an-external-force/48874/4 which also sees the AlreadyClosedException on Azure, but not with the epoch timestamp.

> our write.lock and all other config/data files are in blob storage 

Can you expand on that? Are you using https://github.com/azure-contrib/AzureDirectory or something?

I suspect that this is not something specific to the docker-solr image, and not something we could address. You will be better of asking on the solr-user mailing list.

**Comment by ijmac3** [comment]
Thanks for the response. 

> Can you expand on that? Are you using https://github.com/azure-contrib/AzureDirectory or something?

Certainly. We're just making use of the standard Azure blob storage capabilities to store our solr config/data/logs folders for our solr instance to access. We're not doing anything special with this as far as I'm aware. Some discussion about azure blob storage [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-introduction#azure-storage-services). 

> I suspect that this is not something specific to the docker-solr image, and not something we could address. You will be better of asking on the solr-user mailing list.

Yes, it does look like it's not a problem with docker-solr specifically. Thank you for the help anyway.

**Comment by makuk66** [comment]
> Azure blob storage capabilities to store our solr config/data/logs folders for our solr instance to access

Solr uses the filesystem for its config/data/logs, and the Azure blob storage is an object store, not a file system. You can use blob storage by using a shim layer in Solr, or using a virtual filesystem like [blobfuse](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux). Or are you using [Azure Files](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-introduction), which does expose a filesystem? Or are you using something else? Reason I ask is that it might be that the lock file behaviour you're seeing is an artefact of that layer, rather than Solr or the storage backend.

**Comment by makuk66** [comment]
> Yes, it does look like it's not a problem with docker-solr specifically. Thank you for the help anyway.

OK, I'll close this issue.
