### ISSUE TITLE
Pdfbox tries to create its cache in a non-existant location

### ISSUE THREAD

**Issue by tobia** [docker-solr/docker-solr#252]
Proposed solution: set the cache location to the temporary directory `-Dpdfbox.fontcache=/tmp`

See stack trace:
```
2019-10-07 18:55:49.182 WARN  (Thread-13) [   ] o.a.p.p.f.FileSystemFontProvider New fonts found, font cache will be re-built
2019-10-07 18:55:49.182 WARN  (Thread-13) [   ] o.a.p.p.f.FileSystemFontProvider Building on-disk font cache, this may take a while
2019-10-07 18:55:49.200 WARN  (Thread-13) [   ] o.a.p.p.f.FileSystemFontProvider Could not write to font cache => java.io.FileNotFoundException: /home/solr/.pdfbox.cache (No such file or directory)
  at java.base/java.io.FileOutputStream.open0(Native Method)
java.io.FileNotFoundException: /home/solr/.pdfbox.cache (No such file or directory)
  at java.io.FileOutputStream.open0(Native Method) ~[?:?]
  at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
  at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
  at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
  at java.io.FileWriter.<init>(FileWriter.java:96) ~[?:?]
  at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.saveDiskCache(FileSystemFontProvider.java:300) ~[?:?]
  at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.<init>(FileSystemFontProvider.java:235) ~[?:?]
  at org.apache.pdfbox.pdmodel.font.FontMapperImpl$DefaultFontProvider.<clinit>(FontMapperImpl.java:130) ~[?:?]
  at org.apache.pdfbox.pdmodel.font.FontMapperImpl.getProvider(FontMapperImpl.java:149) ~[?:?]
  at org.apache.pdfbox.pdmodel.font.FontMapperImpl.findFont(FontMapperImpl.java:413) ~[?:?]
  at org.apache.pdfbox.pdmodel.font.FontMapperImpl.getTrueTypeFont(FontMapperImpl.java:321) ~[?:?]
  at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.<init>(PDTrueTypeFont.java:219) ~[?:?]
  at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:75) ~[?:?]
  at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:146) ~[?:?]
  at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:60) ~[?:?]
  at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:848) ~[?:?]
  at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:503) ~[?:?]
  at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:477) ~[?:?]
  at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:150) ~[?:?]
  at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:139) ~[?:?]
  at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:391) ~[?:?]
  at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:147) ~[?:?]
  at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319) ~[?:?]
  at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266) ~[?:?]
  at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:117) ~[?:?]
  at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:172) ~[?:?]
  at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
  at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
  at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) ~[?:?]
  at org.apache.solr.handler.dataimport.TikaEntityProcessor.nextRow(TikaEntityProcessor.java:165) ~[?:?]
  at org.apache.solr.handler.dataimport.EntityProcessorWrapper.nextRow(EntityProcessorWrapper.java:267) ~[?:?]
  at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:476) ~[?:?]
  at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:517) ~[?:?]
  at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:517) ~[?:?]
  at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:415) ~[?:?]
  at org.apache.solr.handler.dataimport.DocBuilder.doFullDump(DocBuilder.java:330) ~[?:?]
  at org.apache.solr.handler.dataimport.DocBuilder.execute(DocBuilder.java:233) ~[?:?]
  at org.apache.solr.handler.dataimport.DataImporter.doFullImport(DataImporter.java:424) ~[?:?]
  at org.apache.solr.handler.dataimport.DataImporter.runCmd(DataImporter.java:483) ~[?:?]
  at org.apache.solr.handler.dataimport.DataImporter.lambda$runAsync$0(DataImporter.java:466) ~[?:?]
  at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by makuk66** [comment]
You can do this without image modification already by running:

```
docker run -it -e SOLR_OPTS="-Dpdfbox.fontcache=/tmp" solr:8.2
```

Or setting it in `/etc/default/solr.in.sh`.

Adding it by default is something to consider... but it with what, and where.
With what: Some might want it in `/var/solr/data` rather than `/tmp`. And I imagine folks might want to override it elsewhere. So we'd want some `${PDFBOX_FONTCACHE:-/tmp}`.
And where: in `docker-entrypoint.sh` (where we set SOLR_PORT), or `/etc/default/solr.in.sh` where all sorts of SOLR_OPTs things (can) get set. I kinda favour the latter, but that's a bit of a faff, in that we currently just copy `/etc/default/solr.in.sh` unmodified.

**Comment by epugh** [comment]
I wonder if this suggestion could be added to the README and closed as an issue?

**Comment by janhoy** [comment]
The core issue here is that solr user's `HOME` folder does not exist or is not writable? In Dockerfile we do not use solr's install script but creates user Wilh

    useradd -r --uid "$SOLR_UID" --gid "$SOLR_GID" "$SOLR_USER"

What if we added `-d /var/solr/` to that line, that would make PDFBox try to write to `/var/solr/.pdfbox.cache` which would succeed. And anyone else relying on HOME folder would also be happy, not only PDFBox? Could be other Tika parsers that also have secret caching?

**Comment by epugh** [comment]
This works for me.   PDFBox is the one I know about.
