### ISSUE TITLE
Allow binding Solr to Privileged ports (<1024)

### ISSUE THREAD

**Issue by janhoy** [docker-solr/docker-solr#263]
If you try to run solr on port 443 like:

    docker run solr:8.3 solr start -p 443 -f

...then you get

    Caused by: java.security.PrivilegedActionException: java.net.SocketException: Permission denied
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1746)

The fix is some trickery with `setcap`. I added these lines to Dockerfile and it worked:

    # Allow to bind to ports < 1024
    RUN setcap CAP_NET_BIND_SERVICE=+eip '/usr/local/openjdk-11/bin/java' && \
        echo "/lib:/usr/local/lib:/usr/lib:/usr/local/openjdk-11/lib:/usr/local/openjdk-11/lib/server:/usr/local/openjdk-11/lib/jli" > /etc/ld-musl-x86_64.path

**Comment by janhoy** [comment]
You also need to apt install `libcap2-bin` for the above to work...

**Comment by makuk66** [comment]
Per https://github.com/moby/moby/issues/38664#issuecomment-460301271, if you have a kernel >4.4 on your docker host, you can this with an unmodified image:

```
docker run -it --sysctl net.ipv4.ip_unprivileged_port_start=0 solr:8.3 solr start -p 443 -f
```

I actually though this would work:

```
docker run -it --cap-add NET_BIND_SERVICE solr:8.3 solr start -p 443 -f
```

but no.

Note that if you are running Solr on port 443 that way, I'd expect that would break some of the scripts that use SOLR_PORT:

```
solr@8235bd8d6482:/opt/docker-solr/scripts$ grep SOLR_PORT *
docker-entrypoint.sh:if [[ -v SOLR_PORT ]] && ! grep -E -q '^[0-9]+$' <<<"${SOLR_PORT:-}"; then
docker-entrypoint.sh:  SOLR_PORT=8983
docker-entrypoint.sh:  export SOLR_PORT
oom_solr.sh:) | tee "$SOLR_LOGS_DIR/solr_oom_killer-$SOLR_PORT-$NOW.log"
solr-create:    if ! wget -O - "http://localhost:${SOLR_PORT:-8983}/solr/admin/cores?action=STATUS" | grep -q instanceDir; then
solr-demo:  if [[ -n "${SOLR_PORT:-}" ]]; then
solr-demo:    post_args+=(-p "$SOLR_PORT")
wait-for-solr.sh:if [[ -v SOLR_PORT ]] && ! grep -E -q '^[0-9]+$' <<<"$SOLR_PORT"; then
wait-for-solr.sh:  echo "Invalid SOLR_PORT=$SOLR_PORT environment variable specified"
wait-for-solr.sh:solr_url="http://localhost:${SOLR_PORT:-8983}"
```

and just also setting SOLR_PORT is not sufficient to make that work.

> The fix is some trickery with setcap. I added these lines to Dockerfile and it worked:
> 
> RUN setcap CAP_NET_BIND_SERVICE=+eip '/usr/local/openjdk-11/bin/java' && \
>    echo "/lib:/usr/local/lib:/usr/lib:/usr/local/openjdk-11/lib:/usr/local/openjdk-11/lib/server:/usr/local/openjdk-11/lib/jli" > /etc/ld-musl-x86_64.path

We can't hardcode the location like that; we'd have to figure it out dynamically (or make it part of tools/update.sh but that would be annoying). That "musl" there sounds like alpine?

**Comment by janhoy** [comment]
Yes, you should set SOLR_PORT var instead of `-p`. 
Could be that the `/etc/ld-xxx.path` file should be something else on ubuntu-slim, but it still works. The location of openjdk I guess is tied to the base image but if the location of the ld-xxx.path file changes depending on where you run the image then it's a bit more tricky.
