### ISSUE TITLE
Velocity throwing HTTP 500

### ISSUE THREAD

**Issue by DigitalFlow** [docker-solr/docker-solr#294]
Hi there,

thanks for providing this project.

We set up version 8.3.1 with the official docker image.
Since we wanted to try out the Velocity UI we made sure that all Velocity specific settings are set inside our solrconfig.xml.

As the velocity loader is disabled by default in 8.3.1 (as the [documentation changelog](https://lucene.apache.org/solr/8_3_1//changes/Changes.html#v8.3.1.upgrade_notes) states as Upgrade Note), we set the application setting "SOLR_OPTS" to "-Dvelocity.solr.resource.loader.enabled=true".
This shows up successfully in the SOLR dashboard JVM Args list.

Unforunately trying to access the Velocity UI for our core still fails with the following HTTP 500 message:

```
Problem accessing /solr/mycorename/browse. Reason:
    {msg=Unable to find resource 'browse.vm',trace=java.io.IOException: Unable to find resource 'browse.vm'
	at org.apache.solr.response.VelocityResponseWriter.getTemplate(VelocityResponseWriter.java:374)
	at org.apache.solr.response.VelocityResponseWriter.write(VelocityResponseWriter.java:152)
	at org.apache.solr.response.QueryResponseWriterUtil.writeQueryResponse(QueryResponseWriterUtil.java:65)
	at org.apache.solr.servlet.HttpSolrCall.writeResponse(HttpSolrCall.java:892)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:594)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:419)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:351)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.base/java.lang.Thread.run(Thread.java:834)
,code=500}
``` 

Did we misconfigure our container, or is something missing in it?
Thanks for your help.

Kind Regards,
Florian

Edit:
What I just found out after fiddling around with a local docker image:
The `browse.vm` file can be found in `/opt/solr/example/files/conf/velocity`.
So when setting this as `template.base.dir` in the velocity handler, velocity starts up (although some images seem broken).

I guess for adjusting those templates, it would be good to create a new mounted storage where I place a copy of the example template and adjust them to my needs?

Maybe it would be useful to default the template.base.dir to the path of the example config so that it does not fail at least. What do you think?

**Comment by makuk66** [comment]
I don't know about the specific issue you're encountering, but you said "we wanted to try out the Velocity UI", and I notice in [the 8.4 upgrade notes](https://lucene.apache.org/solr/guide/8_4/solr-upgrade-notes.html): "The Velocity response writer is also now deprecated and is planned to be removed from Solr in version 9.0.", so perhaps this is not something to invest too much time into?

**Comment by DigitalFlow** [comment]
Hi @makuk66,

thanks a lot for your response.
I did not know that it was deprecated, so thanks for pointing this out.

We do not plan to use this in production, it's just for our customer to get a feeling for which facets he needs.
For anyone stumbling upon this as well: There seems to be an alternative named [blacklight](https://github.com/projectblacklight/blacklight).
I for myself am going to take a look onto it.

Kind Regards,
Florian

**Comment by dsmiley** [comment]
@makuk66 @DigitalFlow : Solr is in the process of plugin-izing and we've identified Velocity as something that is not going to be provided directly by the project at a future point.  So from a 1st party perspective (where Solr itself is the 1st party), Velocity is deprecated.  But merely saying that is misleading because you as a user will be able to get it elsewhere.  It's the first of our plugins to move external: https://github.com/erikhatcher/solritas
These are very early days of the plugin system.  Any way, just know it's not going to vanish.

Maybe @erikhatcher may care to offer advise on why it's not working for you.

@janhoy I think the understandable reaction here demonstrates my point I was trying to make in JIRA about "deprecate" sending the wrong message.
