### ISSUE TITLE
Unable to Add local machine docker desktop solr core to docker hub private repository

### ISSUE THREAD

**Issue by deonticsoft** [docker-solr/docker-solr#325]
I am new in docker. My docker desktop is running on windows 10. I have to run solr in a docker container and then push it to docker private repository hub.

I am following the article https://github.com/docker-solr/docker-solr

I have an azure web app running in Linux with a docker container - which will call the docker image from the docker hub repository private.

http://solrdockerwebapp.azurewebsites.net/solr/#/--this is a web app running on azure.

I have downloaded the solr in docker desktop using PowerShell command.

`docker pull solr:latest 
 
 docker run -d -p 8983:8983 --name my_solr solr:v1`

I checked in the local browser http://localhost:8983/solr/# it is running properly.

I have created a folder in my local machine D drive name test. In this path, I have tried to download the container image files and folder using the below command.
`PS D:\test > docker cp my_solr:/opt/solr/ .`
I can see the docker container (my_solr) all files and folder in my local drive. Now I need to create a new core in solr. Using the below command I have successfully created a solr core and running it on localhost 8983.
`PS D:\test > docker exec -it my_solr solr create_core -c demo_core
PS D:\test > docker exec -it --user=solr my_solr bin/post -c demo_core
example/exampledocs/manufacturers.xml`
Now my task is to push this new core in docker private repository and from there the azure solr web app will be run along with the new demo_core.

Again I have copied the my_solr container newly created solr demo_core files and folder in my local disk, then I have edit the docker file to add the new core folder in the current image, using below command.
`PS D:\test > docker cp my_solr:/var/solr/data .`
I can see the demo_core folder inside the data folder.
I have to edit the docker file like below and build the solr:v1 image again, and commit and push this to the private hub.
`FROM openjdk:11-jre 
ARG SOLR_VERSION="8.5.2" 
ADD data/core_demo /opt/solr-8.5.2/server/solr/configsets 
WORKDIR /opt/solr 
ENTRYPOINT ["docker-entrypoint.sh"] 
CMD ["solr-foreground"]`
Build and Commit the image.
`docker commit my_solr myprivaterepo/solr:latest 
docker push myprivaterepo/solr:latest`

But the cores are not available in solr private repository.
Any suggestions or help will be very helpful.

**Comment by makuk66** [comment]
If you're just trying to get a solr running with a core, there is no need to do any of what you're doing. Just change your azure config to call the image with `solr-precreate mycore` arguments. Get that working first.

If you then want to customise your config, you just need to make the modified config in place, either as a mounted file (or kubernetes config map, or whatever Azure does), or if it's easier, using a private image, see [this example](https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset), which again does the actual core creation on startup with `solr-precreate` rather than trying to create it in the image itself.

**Comment by deonticsoft** [comment]
Hi @makuk66 
Thanks for your reply.
 
How to change the azure config? Azure is only getting the private docker repository images URL. Through this, it is running. Please 
have a look at the below pic.
![image](https://user-images.githubusercontent.com/62342386/86635721-13e4b280-bff1-11ea-8096-118a479a42f4.png)
How to run the solr pre-created command for the  azure web app url 
http://solrdockerwebapp.azurewebsites.net/solr/#/ 
 
We can run any command only in local desktop docker images but is there any way to run the command directly for the docker private repository? For e.g. 

docker exec -it contianername solr create_core -c gettingstarted  // this will create the core in local desktop docker  image  then how to create core on the fly .

I have to edit the local desktop docker's current image container. Copy the newly created solr core folder (soldata/data/demo_core)  from local disk to the current image and then build the image with new tag name. After that checking the files in git hub and run the below commands.

Below is my docker file

FROM openjdk:11-jre 
ARG SOLR_VERSION="8.5.2" 
ADD data/core_demo /opt/solr-8.5.2/server/solr/configsets 
WORKDIR /opt/solr 
ENTRYPOINT ["docker-entrypoint.sh"] 
CMD ["solr-foreground"]
Build and Commit the image.

docker commit my_solr myprivaterepo/solr:latest 
docker push myprivaterepo/solr:latest 
But the most unfortunate thing is core folders are not getting copied over docker private repository . 
Please help , please reply .

**Comment by makuk66** [comment]
> How to change the azure config? 

The only way Azure seems to support is using the "Startup File" there -- you could write a script, add it to your image, and then call that. The script could be a copy of the `docker-entry-point.sh` something like:

```
#!/bin/bash
set -e

# Clear some variables that we don't want runtime
unset GOSU_KEY GOSU_VERSION TINI_KEY TINI_VERSION SOLR_USER SOLR_UID SOLR_GROUP SOLR_GID \
      SOLR_CLOSER_URL SOLR_DIST_URL SOLR_ARCHIVE_URL SOLR_DOWNLOAD_URL SOLR_DOWNLOAD_SERVER SOLR_KEYS SOLR_SHA512

if [[ "$VERBOSE" == "yes" ]]; then
    set -x
fi

if [[ -v SOLR_PORT ]] && ! grep -E -q '^[0-9]+$' <<<"${SOLR_PORT:-}"; then
  SOLR_PORT=8983
  export SOLR_PORT
fi

exec solr-precreate whatever
```

I don't know if it's possible in Azure to mount such files in place when the container starts. If not, then you'll have to make a custom image.
Of course if you're going to create a custom image you can simply change the CMD in your Dockerfile to run `CMD ["solr-precreate", "whatever"]`, and not bother with the separate script.

> I have to edit the local desktop docker's current image container. Copy the newly created solr core folder (soldata/data/demo_core) from local disk to the current image and then build the image with new tag name. 

You keep saying that, but no. Bake the configset into your image, then let the core be created on the fly.
And you probably want to mount a volume in /var/solr, using [volumes](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files) to hold your data.

Just to set your expectation: I am not going to be able to support you setting up an Azure deployment. If you need help, there may be commercial entities able to provide paid consulting.

**Comment by deonticsoft** [comment]
Azure is just run the docker hub image that's all. I don't think there is anything more in there. It's pretty simple.

" Bake the configset into your image, then let the core be created on the fly."

I have a docker hub private repository name deonticsoft/solr:latest .  ( I am new in docker)

How to create a core file or if I run the command in PowerShell 

`docker run -d -p 8983:8983 --name my_solr solr:8 solr-precreate gettingstarted`

Definitely this will create the core folder in my local docker desktop container and it's a local disk , not in a docker hub private repository. Then What is the concept behind create core on the fly? What does this mean? Every single command will be executed on a local machine docker, not in the docker hub.

That's why I think I need to first edit the local machine docker existing image, create core add files, and then build the image and then push to docker private hub. Azure will be simply re-run the newly build docker private image from the docker hub.

My unfortunate thing is after build the edited image and push it to docker private repository, we check the core files are not adding up there. 

https://github.com/docker-solr/docker-solr 
The above tutorial I am following everything working fine in local machine but not in docker hub.

I am following the file dockerfile.template and build this dockerfile like below
`FROM openjdk:11-jre
ARG SOLR_VERSION="8.5.2"
VOLUME /var/solr
EXPOSE 8983
WORKDIR /opt/solr
**COPY data/core_demo opt/solr-8.5.2/server/solr/configsets** this is not working I guess
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["solr-foreground"]`

**Comment by makuk66** [comment]
> What is the concept behind create core on the fly? 

In docker, you create an image (or select a pre-existing image), put that in a registry, then when you want to run a container that uses that image, the image is pulled from the registry. When you run your container, you can pass it information (what command to run, override environment variables), and mount volumes into it. That all happens after the image has been created. The docker-solr image is designed such that you can use it without modification, and have a core automatically created in the container when it first runs (that's what I mean by "on the fly"), before Solr starts: that's what the solr-precreate command does. This is great because (a) you don't need to bother creating a special image, and (b) you can mount a volume at runtime to store the data.

Now, if you want to modify the schema file used to create the core, then you'll need to make that modified schema file available at runtime -- either by mounting that config at runtime, or by creating a custom image where you copy that config in place. Either way, you then specify that config as an argument to solr-precreate, so it can use that config when it creates the core.

So the first question is how to create the config. The [example](https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset) I referenced does that by copying the default config from a (non-running) docker container. Then the choice is whether to mount that config at runtime, or create an image -- I'm not sure how easy Azure supports the former, but you can certainly do the latter, and that seems what you've been doing, so go with that.

Then the question is how to arrange for calling solr-precreate at runtime. Because that's in Azure, and Azure doesn't seem to make that very obvious/easy, and because you're making a custom image anyway, the easiest way is to change the image such that it runs the solr-precreate command when it starts. So at that point: the config is in the image (because you added it), but the core is not. Then when Azure pulls the image and runs the container, the core gets created at that point.

Then the final piece of the puzzle is how to persist that core, so it doesn't disappear when you delete the container. You can do that by mounting a volume at /var/solr (in Azure, at runtime), so that it is in place when solr-precreate creates the core there.

That's the way it's designed to be used.

Now if you're dead-set on creating the core in the image itself rather than using solr-precreate, you could do it, but then you're on your own, and as a beginner you'd find it hard.

**Comment by adarshkumarsingh83** [comment]
hi,
 i am trying to create solr cloud and want to create a core but its failing 
i am following what is suggested by you earlier in this page 
https://github.com/docker-solr/docker-solr

`
version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4
    ports:
      - "2181:2181"
    hostname: zookeeper
    networks:
      - spring-ms

  solr1:
    container_name: solr1
    image: solr:8
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zookeeper:2181
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - employee
    links:
      - zookeeper
    depends_on:
      - zookeeper
    networks:
      - spring-ms

  solr2:
    container_name: solr2
    image: solr:8
    ports:
      - "8984:8983"
    environment:
      - ZK_HOST=zookeeper:2181
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - employee
    links:
      - zookeeper
    depends_on:
      - zookeeper
    networks:
      - spring-ms

networks:
  spring-ms:

volumes:
  data:

`
i am getting exception 
`
SolrException: Could not find collection : employee
solr1        |  at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:116)
solr1        | org.apache.solr.common.SolrException: Could not find collection : employee
solr1        |  at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:116) ~[?:?]
solr1        |  at org.apache.solr.core.CoreContainer.repairCoreProperty(CoreContainer.java:2003) ~[?:?]
solr1        |  at org.apache.solr.cloud.ZkController.checkStateInZk(ZkController.java:1825) ~[?:?]
solr1        |  at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1764) ~[?:?]
solr1        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
solr1        |  at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:802) ~[?:?]
solr1        |  at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.2.jar:4.1.2]
solr1        |  at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
solr1        |  at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:210) ~[?:?]
solr1        |  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
solr1        |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
solr1        |  at java.lang.Thread.run(Unknown Source) [?:?]
solr2        | 2020-08-03 22:57:07.655 INFO  (main) [   ] o.a.s.h.a.MetricsHistoryHandler No .system collection, keeping metrics history in memory.
solr1        | 2020-08-03 22:57:07.644 ERROR (coreContainerWorkExecutor-2-thread-1-processing-n:172.22.0.4:8983_solr) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be loaded on startup => org.apache.solr.common.SolrException: Unable to create core [employee]
solr1        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1327)
solr1        | org.apache.solr.common.SolrException: Unable to create core [employee]
solr1        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1327) ~[?:?]
solr1        |  at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:802) ~[?:?]
solr1        |  at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.2.jar:4.1.2]
solr1        |  at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
solr1        |  at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:210) ~[?:?]
solr1        |  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
solr1        |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
solr1        |  at java.lang.Thread.run(Unknown Source) [?:?]
solr1        | Caused by: org.apache.solr.common.SolrException: 
solr1        |  at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1795) ~[?:?]
solr1        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
solr1        |  ... 7 more
solr1        | Caused by: org.apache.solr.common.SolrException: Could not find collection : employee
solr1        |  at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:116) ~[?:?]
solr1        |  at org.apache.solr.core.CoreContainer.repairCoreProperty(CoreContainer.java:2003) ~[?:?]
solr1        |  at org.apache.solr.cloud.ZkController.checkStateInZk(ZkController.java:1825) ~[?:?]
solr1        |  at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1764) ~[?:?]
solr1        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
solr1        |  ... 7 more
solr1        | 2020-08-03 22:57:07.717 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@10b892d5{/solr,file:///opt/solr-8.5.2/server/solr-webapp/webapp/,AVAILABLE}{/opt/solr-8.5.2/server/solr-webapp/webapp}
solr1        | 2020-08-03 22:57:07.730 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@31e75d13{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8983}
solr1        | 2020-08-03 22:57:07.730 INFO  (main) [   ] o.e.j.s.Server Started @4867ms
solr2        | 2020-08-03 22:57:07.758 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.node' (registry 'solr.node') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@b978d10
solr2        | 2020-08-03 22:57:07.758 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jvm' (registry 'solr.jvm') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@b978d10
solr2        | 2020-08-03 22:57:07.764 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jetty' (registry 'solr.jetty') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@b978d10
solr2        | 2020-08-03 22:57:07.801 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /var/solr/data
solr2        | 2020-08-03 22:57:07.802 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Cores are: [employee]
solr2        | 2020-08-03 22:57:07.814 ERROR (coreLoadExecutor-9-thread-1-processing-n:172.22.0.3:8983_solr) [c:employee   x:employee] o.a.s.c.ZkController  => org.apache.solr.common.SolrException: Could not find collection : employee
solr2        |  at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:116)
solr2        | org.apache.solr.common.SolrException: Could not find collection : employee
solr2        |  at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:116) ~[?:?]
solr2        |  at org.apache.solr.core.CoreContainer.repairCoreProperty(CoreContainer.java:2003) ~[?:?]
solr2        |  at org.apache.solr.cloud.ZkController.checkStateInZk(ZkController.java:1825) ~[?:?]
solr2        |  at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1764) ~[?:?]
solr2        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
solr2        |  at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:802) ~[?:?]
solr2        |  at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.2.jar:4.1.2]
solr2        |  at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
solr2        |  at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:210) ~[?:?]
solr2        |  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
solr2        |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
solr2        |  at java.lang.Thread.run(Unknown Source) [?:?]
solr2        | 2020-08-03 22:57:07.825 ERROR (coreContainerWorkExecutor-2-thread-1-processing-n:172.22.0.3:8983_solr) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be loaded on startup => org.apache.solr.common.SolrException: Unable to create core [employee]
solr2        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1327)
solr2        | org.apache.solr.common.SolrException: Unable to create core [employee]
solr2        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1327) ~[?:?]
solr2        |  at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:802) ~[?:?]
solr2        |  at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.2.jar:4.1.2]
solr2        |  at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
solr2        |  at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:210) ~[?:?]
solr2        |  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
solr2        |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
solr2        |  at java.lang.Thread.run(Unknown Source) [?:?]
solr2        | Caused by: org.apache.solr.common.SolrException: 
solr2        |  at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1795) ~[?:?]
solr2        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
solr2        |  ... 7 more
solr2        | Caused by: org.apache.solr.common.SolrException: Could not find collection : employee
solr2        |  at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:116) ~[?:?]
solr2        |  at org.apache.solr.core.CoreContainer.repairCoreProperty(CoreContainer.java:2003) ~[?:?]
solr2        |  at org.apache.solr.cloud.ZkController.checkStateInZk(ZkController.java:1825) ~[?:?]
solr2        |  at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1764) ~[?:?]
solr2        |  at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
solr2        |  ... 7 more

`

**Comment by makuk66** [comment]
`solr-precreate` is for standalone Solr deployments only. For SolrCloud deployments [example](https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml), you have to create the core later (once Solr has started), through the UI or API or solr command in some other container. There's no docker-solr-specific functionality to assist with that.
