### ISSUE TITLE
DIH to import from MSSQL gives error no sqljdbc_auth in java.library.path

### ISSUE THREAD

**Issue by xcellenceit** [docker-solr/docker-solr#330]
Using Solr latest, I need to import a data using DIH from MSSQL Server. 

I am currently loading sqljdbc42.jar and copying it at /opt/solr/contrib/dataimporthandler/ to load the same. 

Now I am getting following error...
```
Full Import failed:java.lang.RuntimeException: java.lang.RuntimeException: org.apache.solr.handler.dataimport.DataImportHandlerException: Unable to execute query....

Caused by: java.lang.UnsatisfiedLinkError: no sqljdbc_auth in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at com.microsoft.sqlserver.jdbc.AuthenticationJNI.<clinit>(AuthenticationJNI.java:41)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3132)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:43)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3123)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1981)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1628)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1459)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:773)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1168)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
```
Kindly advise how to fix this and use DIH to import data from MSSQL with Docker?

**Comment by makuk66** [comment]
Per [question1](https://stackoverflow.com/questions/23949890/java-lang-unsatisfiedlinkerror-no-sqljdbc-auth-in-java-library-path), [question2](https://stackoverflow.com/questions/30914061/connect-to-sql-server-from-linux-via-jdbc-using-integratedsecurity-windows-auth) and [the Microsoft docs](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15#Connectingintegrated), it sounds like options are: (a) run with `integratedSecurity=false`, (b) use Kerberos, or (c) use Windows

**Comment by xcellenceit** [comment]
Using integratedSecurity=false, resolved the issue. Thanks
